services:
  - type: web
    name: partner-portal-frontend
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: npm start
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: API_URL
        fromService:
          type: web
          name: partner-portal-backend
          property: host
